config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'
  get 'login' => "user_sessions#new", :as => :login
  get 'log_in' => "user_sessions#new", :as => :log_in
  get 'signin' => "user_sessions#new", :as => :signin
  get 'sign_in' => "user_sessions#new", :as => :sign_in
  get 'logout' => "user_sessions#destroy", :as => :logout
  get 'signup' => 'users#new', :as => :signup
  get 'sign_up' => 'users#new', :as => :sign_up
  get 'register' => 'users#new', :as => :register
  get 'user_sessions/new'
  get 'welcome/index'
  resources :user_sessions
  resources :users
  resources :posts

  root 'welcome#index'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  message    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Post < ActiveRecord::Base
  belongs_to :user
  validates :message, presence: true,
            length: { minimum:2, maximum:140  }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                :integer          not null, primary key
#  email             :string
#  first_name        :string
#  last_name         :string
#  crypted_password  :string(128)      default(""), not null
#  password_salt     :string(128)      default(""), not null
#  persistence_token :string
#  login_count       :integer          default(0)
#  last_request_at   :datetime
#  current_login_at  :datetime
#  last_login_at     :datetime
#  current_login_ip  :string
#  last_login_ip     :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  accepts_nested_attributes_for :posts, allow_destroy: true

  acts_as_authentic do |opts|
    opts.merge_validates_length_of_password_field_options(
        {
            minimum: 8,
            message: 'Your password is too short!'
        })
  end

  #validation
  validates :email, presence: true, uniqueness: true,
            length: {within: 7..40},
            format: {with: /\A(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6}\z/i }
  validates :first_name, presence: true, length: {within: 2..30}
  validates :last_name, presence: true, length: {within: 2..30}

  def full_name
    self.first_name.titleize + ' ' + self.last_name.gsub('O\'','O\' ').titleize.gsub('O\' ','O\'')
  end
  
  before_save :save_user_md5
  def save_user_md5
    self.img_mb5 = Digest::MD5.hexdigest(self.email)
  end
  def adorable_avatar(size)
    hash = self.img_mb5
    size = "#{size}x#{size}"
    src = "http://api.adorable.io/avatars/#{size}/#{hash}.png"
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
# configuration here, see documentation for sub-modules
# of Authlogic::Session
  logout_on_timeout true
  consecutive_failed_logins_limit 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # helper :all
  helper_method :current_user_session, :current_user
  private
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end

  def logged_in_required
    unless current_user
      store_location
      flash[:error] = 'You must be logged in to access this page'
      redirect_to sign_in_url
      return false
    end
  end

  def logged_out_required
    if current_user
      flash[:error] = 'You must be logged out to access this page'
      redirect_to root_url
      return false
    end
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def redirect_back_or_default(default)
    if session[:return_to]
      destination = session[:return_to]
      session[:return_to] = nil
    else
      destination = default
      session[:return_to] = nil
    end
    redirect_to(destination)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_required
  def index
    #@posts = current_user.posts.order(created_at: :desc)
    @posts = Post.all.order(created_at: :desc).paginate(:page => params[:page], per_page: 5)
    #another way of doing this
    #@posts = Post.where(user_id:current_user.id).order(created_at: :desc)
    @post = Post.new
    #@post.user_id = current_user.id
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      render partial: "post", locals: {post: @post}
    else
      render json: @post.errors, status: 422
    end
  end

  def show
    @post = Post.find(params[:id])
    # code to deny the access permission
    # if @post.user != current_user
    #   flash[:alert] = 'No permission for you'
    #   redirect_to root_path
    # end
    # OR
    # @post.current_user.orders.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:message)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :logged_out_required, only: [:new, :create]
  before_filter :logged_in_required, only: :destroy
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params)
    if @user_session.save
      flash[:success] = "Welcome back!"
      redirect_to root_url
    else
      render action: :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:success] = "You are now logged out"
    redirect_to root_url
  end

  private
  def user_session_params
    params.require(:user_session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'digest/md5'
  include ApplicationHelper
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :logged_in_required, :except => [:new, :create]
  respond_to :json, :html
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have successfully sign up!"
      redirect_to posts_path
    else
        render :new
    end
  end


  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def format_date(date)
    date.strftime('%A %B %C at %H:%M')
  end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Twitter
    = stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    /.main_container  class="#{ !current_user ? 'session_exists' : 'background_image'}"
    .main_container  class="#{!current_user ? 'container_log_in' : nil}"
      - if current_user
        .navbar.navbar-default
          .container-fluid
            .navbar-header
             h2
              | Mini-Twi
              span id="navi-sign-in-span"
                small
                  | Signed in as:
                  span #{current_user.full_name}
            .nav.navbar-nav.navbar-right
              span.nav_logout
                h3
                  = link_to "Logout", logout_path

      == yield

app/views/posts/_post.html.slim
li.panel-body
  p
    -if current_user == post.user
      =link_to(image_tag(post.user.adorable_avatar(50), size: '50x50', alt: "The profile image of " + post.user.first_name), user_path(post.user_id), title: post.user.full_name )
    - else
      =link_to(image_tag(post.user.adorable_avatar(50), size: '50x50', alt: "The profile image of " + post.user.first_name), post_path(post.id), title: post.user.full_name )
    span#post-content-span
      = link_to post.message, post_path(post.id), id: "post-content-link"
  -if current_user == post.user
    span#destroy-span
      = link_to 'Destroy', post_path(post.id), method: :delete, id: "destroy-post-link"
    span#date-span
      =format_date(post.created_at)
  -else
    span#date-span_others
      = format_date(post.created_at)
br

app/views/posts/index.html.slim
/.panel.panel-info
/  .panel-heading
/    p
/      span
/        | Signed in as:
/        b= current_user.full_name
/      span.float-right
/        = link_to "Logout", logout_path

/.container_fluid
/  .panel.panel-info
/    .panel-heading
/      .row
/        .col-xs-12.col-sm-6.col-md-8
/          span.nav_sign_in
/            | Signed in as:
/            span #{current_user.full_name}
/        .col-xs-6.col-md-4
/          span.nav_logout
/            = link_to "Logout", logout_path
.container
  = form_for(@post, remote:true) do|f|
    p align="center"
      = f.text_area :message, cols: "50", rows: "4", placeholder:"What's happening?"
    #word-count-plus-commit-div
      #words-record-button-div
        span#word-count-span.float-left
        span#words-count 140
        span characters left!
        span#create-post-span.float-right
          = f.submit value= "Create", id:"create-post-link", class:"btn btn-info"
.container
  ol#posts
    = render @posts
    = will_paginate @posts

app/views/posts/show.html.slim
.container
  .jumbotron
    h2 = @post.message
    h5
     |Created:
     =format_date(@post.created_at)
    span class="glyphicon glyphicon-triangle-left"
      = link_to posts_path do
        span Back

app/views/user_sessions/_form.html.slim
= form_for @user_session, as: :user_session, url: { action: :create } do |f|
  -if @user_session.errors.any?
    #error_explanation
      h2
        = pluralize(@user_session.errors.count, 'error')
        | prevented you from logging in:
        ul
          -@user_session.errors.full_messages.each do |message|
            li = message
  .form-group
    = f.text_field :email, class: "form-control input-lg", placeholder: "Email:"
  .field
    = f.password_field :password,  class: "form-control input-lg", placeholder: "Password:"
  .actions
    = f.submit 'Sign in', class:"btn btn-primary btn-lg btn-block"

app/views/user_sessions/new.html.slim
div class="modal show" tabindex="-1" role="dialog" aria-hidden="true"
  .modal-dialog id="sign-in-model-dialog"
    .modal-content id="sign-in-model-content"
      .modal-header
        h1 id="my-welcome-heading"
          span class="label label-default" Please Sign in!
      .modal-body
        = render 'form'
      .modal-footer
        =link_to sign_up_path do
          span Sign up!

app/views/users/_edit.html.slim
= form_for(@user) do |f|
  -if @user.errors.any?
    #error_explanation
      h2 = pluralize(@user.errors.count, "error")
      | prohibited this user from being saved:
      ul
         -@user.errors.full_messages.each do |message|
          li = message
  .field
      = f.text_field :first_name,  class:"form-control input-lg", placeholder:"First Name:"
  .field
      = f.text_field :last_name, class:"form-control input-lg", placeholder:"Last Name:"
  .field
      = f.text_field :password,  class:"form-control input-lg", placeholder:"Password:"
  .field
      = f.text_field :password_confirmation,  class:"form-control input-lg", placeholder:"Password Confirmation:"
  .actions
    h2.text-center
      = f.submit 'Update User', class:"btn btn-primary"

app/views/users/_form.html.slim
= form_for(@user) do |f|
  -if @user.errors.any?
    #error_explanation
      h2 = pluralize(@user.errors.count, "error")
      | prohibited this user from being saved:
      ul
         -@user.errors.full_messages.each do |message|
          li = message
  .field
     = f.text_field :email, class:"form-control input-lg", placeholder:"Email:"
  .field
     = f.text_field :first_name,  class:"form-control input-lg", placeholder:"First Name:"
  .field
     = f.text_field :last_name, class:"form-control input-lg", placeholder:"Last Name:"
  .field
     = f.password_field :password,  class:"form-control input-lg", placeholder:"Password:"
  .field
     = f.password_field :password_confirmation,  class:"form-control input-lg", placeholder:"Password Confirmation:"
  .actions
     = f.submit 'Create User', class:"btn btn-primary btn-lg btn-block"

app/views/users/edit.html.slim
.modal.show tabindex="-1" role="dialog" aria-hidden="true"
  .modal-dialog id="edit-model-dialog"
    .modal-header style="margin-top: 100px"
      h2.text-center
        .label.label-default
          | Editing User
    .modal-body
      = render 'edit'
    .modal-footer
      = link_to 'Back', posts_path

app/views/users/new.html.slim
.modal.show aria-hidden="true" role="dialog" tabindex="-1"
  #sign-up-model-dialog.modal-dialog
    #sign-up-model-content.modal-content
      .modal-header
        h1#my-welcome-heading
          span.label.label-default Please Sign up!
      .modal-body
        = render 'form'
      .modal-footer
        = link_to 'Back to sign in', users_path

app/views/users/show.html.slim
.container-fluid
  .jumbotron
    .btn.btn-info data-toggle="collapse" data-target="#demo" type="button"
      | User Name:
    .collapse id="demo"
      | Email:
      = @user.email
    p
      | First name:
      = @user.first_name
    p
      | Last name:
      = @user.last_name
    = link_to 'Edit', edit_user_path(@user)
    ||
    = link_to 'Back', posts_path

app/views/welcome/index.html.slim
.container
  - if current_user
    .page-header
      h2 id="my-welcome-heading"
        span class="label label-default"
          | Welcome to Twitter!
    p
      span class="glyphicon glyphicon-triangle-right"
      == link_to posts_path do
        span  Start Twitter!
  - else
    .jumbotron
      p
        span class="glyphicon glyphicon-triangle-left"
        == link_to sign_in_path do
          span  Sign in first!